// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf7PSi-3Y3Wym61TmCHUH2ZYWPta0mZKA',
    appId: '1:1023325779321:web:1c2422f2d52f5e0eaeeba8',
    messagingSenderId: '1023325779321',
    projectId: 'chat-app-a7941',
    authDomain: 'chat-app-a7941.firebaseapp.com',
    storageBucket: 'chat-app-a7941.appspot.com',
    measurementId: 'G-DWW4LV2FQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDShXhoK1aasBthF9flEf8UCM-9lwPkqR0',
    appId: '1:1023325779321:android:09a90000abf973adaeeba8',
    messagingSenderId: '1023325779321',
    projectId: 'chat-app-a7941',
    storageBucket: 'chat-app-a7941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVotGMGcxUu9KuWIOmKwqP_Dq9d5nh86c',
    appId: '1:1023325779321:ios:e1d3d4df360b86d1aeeba8',
    messagingSenderId: '1023325779321',
    projectId: 'chat-app-a7941',
    storageBucket: 'chat-app-a7941.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVotGMGcxUu9KuWIOmKwqP_Dq9d5nh86c',
    appId: '1:1023325779321:ios:e1d3d4df360b86d1aeeba8',
    messagingSenderId: '1023325779321',
    projectId: 'chat-app-a7941',
    storageBucket: 'chat-app-a7941.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf7PSi-3Y3Wym61TmCHUH2ZYWPta0mZKA',
    appId: '1:1023325779321:web:4da543fabf879200aeeba8',
    messagingSenderId: '1023325779321',
    projectId: 'chat-app-a7941',
    authDomain: 'chat-app-a7941.firebaseapp.com',
    storageBucket: 'chat-app-a7941.appspot.com',
    measurementId: 'G-70E98JDJTS',
  );
}
